### ISSUE TITLE
Question on building the AuthenticatorSelectionCriteria

### ISSUE THREAD

**Issue by witrisna** [googlecodelabs/fido2-codelab#12]
https://github.com/googlecodelabs/fido2-codelab/blob/ac04b3e8d29a1c6f77ce8aea99b5fe943bf68f4d/android/app/src/main/java/com/example/android/fido2/api/AuthApi.kt#L369

When preparing the AuthenticatorSelectionCriteria (https://developers.google.com/android/reference/com/google/android/gms/fido/fido2/api/common/AuthenticatorSelectionCriteria) using the Builder (https://developers.google.com/android/reference/com/google/android/gms/fido/fido2/api/common/AuthenticatorSelectionCriteria.Builder), the builder does not allow to set the requireResidentKey and userVerification which defined in the spec
https://www.w3.org/TR/webauthn/#dom-authenticatorselectioncriteria-requireresidentkey, is there a reason for that?

**Comment by agektmr** [comment]
I don't think skipping those values mean much.
@yaraki any particular reasons?

**Comment by witrisna** [comment]
The residentkey provides a username-less experience. When setting the requireResidentKey to true, will direct the authenticator to create a new resident credential for short. With resident credentials, the authenticator is able to select the appropriate credential private key based on the relying party ID.

**Comment by agektmr** [comment]
Resident keys are not supported on Android yet anyway.

**Comment by witrisna** [comment]
Do you know if Google plans to support it, any channel that I can ask about it?

**Comment by agektmr** [comment]
Yes, we plan to support it, but can't tell when.

**Comment by witrisna** [comment]
Thanks for the information.

**Comment by mreedr** [comment]
@agektmr I know this thread is old, but I'm running into the same issue as @witrisna . Are there any solutions that have come up since this thread? I'm in dire need of saving _some kind_ of information with the authenticator to allow the usernameless flow. My app is completely clientside and saving username/id information is critical.

**Comment by tarrencev** [comment]
@mreedr did you figure out a solution here?

**Comment by lucidnx** [comment]
Is there any progress? Google is one of first who implemented FIDO and now we are waiting years to get "passwordless" sign in on Android... It's totaly inconsistent as of now, I am disappointed.
There is even not proper dark theme on selection of type of HW key (USB/NFC/BT..). black font on dark background, outdated UI.

**Comment by agektmr** [comment]
You can already use the resident key (discoverable credential) in Android. To try that I recommend you check out https://codelabs.developers.google.com/credential-manager-api-for-android .

This codelab is outdated. We are considering revising it but no specific timeline.

**Comment by lucidnx** [comment]
> You can already use the resident key (discoverable credential) in Android. To try that I recommend you check out https://codelabs.developers.google.com/credential-manager-api-for-android .
> 
> This codelab is outdated. We are considering revising it but no specific timeline.

Sure but I am not able to use chrome with yubikey and resident keys yet. even other apps don't support resident keys. I am not developer of android apps but I see there is some API that should be used within apps? Why is it not yet working with android when there's support for it?

**Comment by agektmr** [comment]
Unfortunately, roaming authenticators with resident keys are not supported yet in Android. We are working on it.

**Comment by lucidnx** [comment]
> 

Is there some ETA?
