### ISSUE TITLE
Fido2ApiClient to manage the registered credentials

### ISSUE THREAD

**Issue by witrisna** [googlecodelabs/fido2-codelab#14]
I have been successfully performing webAuthn registration and authenticate with Fido2ApiClient (https://developers.google.com/android/reference/com/google/android/gms/fido/fido2/Fido2ApiClient), is there any interface that I can manage the registered credentials, so that I can query or delete the existing credentials?

My Application maintains the webAuthn state (for e.g. The device has been registered), however, when the user clears storage either on the App or Google Play Services, 

![image](https://user-images.githubusercontent.com/18559472/103975589-56ff1a00-5129-11eb-96b4-1c7b69fc319f.png)

the state will be out of sync. Instead for the App to maintain the state, is there any interface we can query or delete the stored credentials from Google Play Services?

**Comment by agektmr** [comment]
@witrisna No. You can't delete keys stored to the Play Services.

**Comment by witrisna** [comment]
Thanks for the information.
