### ISSUE TITLE
Instructions use wrong keystore

### ISSUE THREAD

**Issue by mikegb** [googlecodelabs/fido2-codelab#15]
Hey all, thank you for this code lab it was very helpful. I just wanted to point out an issue I spent a little while debugging earlier that might be fixed in the documentation. Perhaps this is the wrong place to report this, so please feel free to close if so.

This page https://codelabs.developers.google.com/codelabs/fido2-for-android/#2 mentions 

> In order to get the SHA256 hash of your developer signing certificate, use the command below. The default password of the debug keystore is "android".
> `$ keytool -exportcert -list -v -alias androiddebugkey -keystore ~/.android/debug.keystore`

However this code is set up to use a keystore in `android/debug.jks`. This took a bit to debug and I figured it might be worth mentioning in the documentation.

**Comment by agektmr** [comment]
@yaraki can you take a look at this?
