### ISSUE TITLE
Is the server down?

### ISSUE THREAD

**Issue by romaopedro** [googlecodelabs/fido2-codelab#6]
I just installed the app and tried to do a login but I got an HTTP timeout connection.

Is the server up and running or is it just this endpoint that was removed?
https://webauthn-codelab.glitch.me/auth/username

**Comment by agektmr** [comment]
Hi @romaopedro , thanks for the report.
Glitch had trouble and the code on the repo has been completely vanished.
Luckily, I had a copy at https://webauthn-codelab-resolution.glitch.me and I'll try to resurrect from it, but please allow me a week or two.

**Comment by romaopedro** [comment]
@agektmr thank you. I'll wait for your feedback with good news.

**Comment by agektmr** [comment]
@romaopedro Sorry for getting back to you late, but the server should be back and running now. Please close this issue if you confirm that it's working.
