### ISSUE TITLE
Unable to perform exemple

### ISSUE THREAD

**Issue by DestruidorPT** [googlecodelabs/fido2-codelab#7]
Hello

I was to unable to perform the desired functionality and also i download the apk (that is available) and is always crashing.

**This error happens sometimes when I submit username, the same happens in the apk that is available.**

``
E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-5 Process: com.example.android.fido2, PID: 14386 java.lang.NullPointerException: null reference at com.google.android.gms.common.internal.Preconditions.checkNotNull(Unknown Source:2) at com.google.android.gms.fido.fido2.api.common.PublicKeyCredentialRequestOptions.<init>(Unknown Source:5) at com.google.android.gms.fido.fido2.api.common.PublicKeyCredentialRequestOptions$Builder.build(Unknown Source:17) at com.example.android.fido2.api.AuthApi.parsePublicKeyCredentialRequestOptions(AuthApi.kt:317) at com.example.android.fido2.api.AuthApi.signinRequest(AuthApi.kt:246) at com.example.android.fido2.repository.AuthRepository$signinRequest$1.run(AuthRepository.kt:361) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:764) D/EGL_emulation: eglMakeCurrent: 0xe64667c0: ver 3 0 (tinfo 0xe63b1b60)
``

**This error happens whenever I ask to add a credential.**

``
E/AuthRepository: Cannot call registerRequest java.lang.IllegalArgumentException: com.google.android.gms.fido.fido2.api.common.COSEAlgorithmIdentifier$UnsupportedAlgorithmIdentifierException: Algorithm with COSE value -8 not supported at com.google.android.gms.fido.fido2.api.common.PublicKeyCredentialParameters.<init>(Unknown Source:11) at com.example.android.fido2.api.AuthApi.parseParameters(AuthApi.kt:449) at com.example.android.fido2.api.AuthApi.parsePublicKeyCredentialCreationOptions(AuthApi.kt:335) at com.example.android.fido2.api.AuthApi.registerRequest(AuthApi.kt:152) at com.example.android.fido2.repository.AuthRepository$registerRequest$1.run(AuthRepository.kt:253) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:764) Caused by: com.google.android.gms.fido.fido2.api.common.COSEAlgorithmIdentifier$UnsupportedAlgorithmIdentifierException: Algorithm with COSE value -8 not supported at com.google.android.gms.fido.fido2.api.common.COSEAlgorithmIdentifier.fromCoseValue(Unknown Source:10) at com.google.android.gms.fido.fido2.api.common.PublicKeyCredentialParameters.<init>(Unknown Source:8) at com.example.android.fido2.api.AuthApi.parseParameters(AuthApi.kt:449)  at com.example.android.fido2.api.AuthApi.parsePublicKeyCredentialCreationOptions(AuthApi.kt:335)  at com.example.android.fido2.api.AuthApi.registerRequest(AuthApi.kt:152)  at com.example.android.fido2.repository.AuthRepository$registerRequest$1.run(AuthRepository.kt:253)  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)  at java.lang.Thread.run(Thread.java:764) 
``

Another thing I'm also trying to implement using Yubico NFC (security key) instead of the fingerprint, can you tell me where the documentation is, and maybe add in the exercise the location of the documentation where it says how to use security keys with Fido2.

**Comment by agektmr** [comment]
@yaraki can you have a look?

**Comment by agektmr** [comment]
@DestruidorPT There were defects in the server while replacing the library, but they should have been resolved by now.
